### PR TITLE
Added sort feature

### PR DESCRIPTION
**Pull request by PankajR007**
Added a sort feature that allows the user to sort from A-Z alphabets and Z-A alphabets. 

Before screenshot :
image

After screenshot: (A-Z)
image

(Z-A)
image

@shreyamalogi Please review the PR

### CODE REVIEW

**Comment by shreyamalogi** [comment]
Well done!! 
#166

**Comment by PankajR007** [comment]
@shreyamalogi  The PR is Merged but it is showing that has not been assigned to me. Please assign this PR to me, and close the issue as completed.

**Comment by shreyamalogi** [comment]
Issue #166, previously assigned to you, has been successfully resolved. You submitted a pull request, which has been reviewed and merged and marked as completed. @PankajR007

**Comment by PankajR007** [comment]
@shreyamalogi This PR needs to be assigned to  me right?

**Comment by shreyamalogi** [comment]
@PankajR007 Only the issue will be assigned, and its resolution will be submitted via PR. You have completed the task, no need to worry.

**Comment by PankajR007** [comment]
@shreyamalogi okay Thank you

**Pull request merged**
